### ISSUE TITLE
Set date/time

### ISSUE THREAD

**Issue by grischard** [rytilahti/python-eq3bt#11]
The misbehaviour on https://github.com/home-assistant/home-assistant/issues/3885 makes me believe that thermostat date and time can be set over bluetooth. It would be nice to be able to sync date and time on the devices.

**Comment by rytilahti** [comment]
Yes, the date and time are set during the update call as can be seen here: https://github.com/rytilahti/python-eq3bt/blob/master/eq3bt/eq3btsmart.py#L158 . IIRC it didn't used to be set during the update at some point causing those issues, which is why it is now done implicitly.

**Comment by jannau** [comment]
The current date and time are part of the update command. The thermostat accepted shorter update commands but apparently used then uninintialized data as date and time causing problems when using the automatic mode with schedules.
So it's already done and this ticket can be closed.
