### ISSUE TITLE
Setting schedule 

### ISSUE THREAD

**Issue by Dannsei** [rytilahti/python-eq3bt#17]
Many thanks for this. Having this control over the valves is great.

Would it be possible to get an example of usage for setting a schedule for a given day using the set_schedule method. I'm not sure what needs to be passed to the data parameter.

**Comment by c-mauderer** [comment]
I just had the same problem and I needed quite a while to figure it out. Not really easy if you don't use this advanced Python stuff like Construct. Here's my solution:
```
from datetime import time
from eq3bt import Thermostat
from eq3bt import HOUR_24_PLACEHOLDER as END_OF_DAY

thermostat = Thermostat('12:34:56:78:9A:BC')
thermostat.set_schedule(
    dict(
        cmd="write",
        day="sun",
        base_temp=18,
        next_change_at=time(8, 0),
        hours=[
            dict(target_temp=23, next_change_at=time(20, 0)),
            dict(target_temp=18, next_change_at=END_OF_DAY),
            dict(target_temp=23, next_change_at=END_OF_DAY),
            dict(target_temp=23, next_change_at=END_OF_DAY),
            dict(target_temp=23, next_change_at=END_OF_DAY),
            dict(target_temp=23, next_change_at=END_OF_DAY)
        ]
    )
)
```

**Comment by rytilahti** [comment]
Feel free to create a PR to add this to the readme (and then this can be closed) :-)

**Comment by c-mauderer** [comment]
Sorry, I've been lazy yesterday. So I just dropped it here. I created a pull request.
