### ISSUE TITLE
Can't connect to EQ3-Device

### ISSUE THREAD

**Issue by Paragrimm** [rytilahti/python-eq3bt#2]
https://hastebin.com/efenojejes.sql

The 2 Thermostats before worked, I assume that's because of the range/signal-strength?!

**Comment by rytilahti** [comment]
Hard to say what's the real cause here (it just can't connect, bt module busy is one possibility), but eq3cli should handle it graciously anyway.

**Comment by DirkHeinke** [comment]
I have the problem if I click in the UI to fast or do this:
`eq3cli --mac 00:1A:22:05xx temp & eq3cli --mac 00:1A:22:05xx temp`

Home Assistant seems to call the tool with multiple Threads. Perhaps there is a way to create a lockfile or prevent HA from using the tool concurrent?

**Comment by Paragrimm** [comment]
I was (and still am lol) stupid. I somehow entered a completely wrong MAC Adress. So well, I'll close this issue. But thanks for putting some thinking into my dumbness :D. Have a great day everyone!

**Comment by rytilahti** [comment]
Nice to hear that it was just about invalid mac. @DirkHeinke you should not probably be calling it twice in a row like that, depending on your bt setup ;-)

Anyway, I'm hoping that at some point there will be a nice way for handling bt connectivity in general (through bluez dbus interface, or making centralized, sequential updates for bt devices). Having a separate lock file for every bt component in homeassistant doesn't sound very reasonable.
