### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by berrywhite96** [rytilahti/python-eq3bt#23]
Hi,
project works pretty well on python 3, but on python 2 I dont get any feedback from the device. Also I didnt get any exceptions which could be syntax problems. Basic code like this, doesnt work:
`>>> from eq3bt import Thermostat
>>> th = Thermostat("XX:XX:XX:XX:XX:XX")
>>> th.update()
>>> th.target_temperature
<Mode.Unknown: -1>`
Thanks anyway!

**Comment by rytilahti** [comment]
Python 2 is not supported by this library (unfortunately I had forgotten to add this requirement to setup.py although it is there when one tries to use the cli tool), nor is planned to be supported so I'm closing this.
