### ISSUE TITLE
Question / Not an issue

### ISSUE THREAD

**Issue by dimovnike** [rytilahti/python-eq3bt#27]
Hello,
anyone have an idea how come it works without any pairing? The device is paired to my phone but it successfully works from the home-assistant and it can even change settings. Any idea how the access can be restricted? Thanks.

**Comment by rytilahti** [comment]
I have no idea how the "pairing" from the app works, but there is no real security in these devices so that's why it works. I don't think there is a way to restrict access (besides this getting fixed in the firmware of the devices).
