### ISSUE TITLE
Helper wasn't build

### ISSUE THREAD

**Issue by Paragrimm** [rytilahti/python-eq3bt#3]
https://hastebin.com/olunadaged.sql

The bluepy library didn't build the Helper

(since we chatted in Gitter and this was the wrong error, I'll paste you the other errors in here aswell in the right order)
#1 https://hastebin.com/gebavefili.sql
#2 https://hastebin.com/fuwafabefi.sql
#3 https://hastebin.com/wininoxike.sql
#4 https://hastebin.com/uzokibedob.sql
#5 https://hastebin.com/cujosihofi.sql
#6 https://hastebin.com/jetezuliso.sql
#7 would be the one from above: https://hastebin.com/olunadaged.sql

**Comment by stefanvermaas** [comment]
I also got troubles with building the helper. Is there already any update on this @rytilahti ?

<img width="1786" alt="schermafbeelding 2017-02-22 om 00 38 58" src="https://cloud.githubusercontent.com/assets/1470863/23190307/62d760f6-f897-11e6-8dcb-41bbdc9a07e5.png">

**Comment by klemens** [comment]
The helper was also not built automatically for me, but it built fine manually using the included Makefile. But shouldn't this be reported to [bluepy](https://github.com/IanHarvey/bluepy) instead?

@stefanvermaas: It seems you don't have gcc installed?

**Comment by rytilahti** [comment]
The module it doesn't check properly if the mac is passed, that's one part of the original problem. However, the problem with bluepy-helper not being built is upstream one https://github.com/IanHarvey/bluepy/issues/158 . I asked the original reporter to report this as a reminder for myself to fix that passing an empty mac should be checked (however, bluepy shouldn't raise an exception like that even with an invalid mac).

**Comment by rytilahti** [comment]
Closed with #4.
