### ISSUE TITLE
Failed to connect to peripheral

### ISSUE THREAD

**Issue by marco-gallinari** [rytilahti/python-eq3bt#37]
Hello,

I am trying to connect to a brand new eqiva eq3 thermostat.
The device is new, with full capacity batteries, installed a feet away from the computer I'm using to test connection.
I've configured the thermostat via android app, and it works correctly when connected.
But if I disconnect the thermostat from the phone and I try to read the device state via eq3cli, this is the output:

```
eq3cli --mac 00:xx:xx:xx:xx:0f --debug
DEBUG:eq3bt.eq3btsmart:Querying the device..
DEBUG:eq3bt.connection:Trying to connect to 00:1a:22:13:9c:0f
DEBUG:eq3bt.connection:Unable to connect to the device 00:1a:22:13:9c:0f, retrying: Failed to connect to peripheral 00:1a:22:13:9c:0f, addr type: public
DEBUG:eq3bt.connection:Second connection try to 00:1a:22:13:9c:0f failed: Failed to connect to peripheral 00:1a:22:13:9c:0f, addr type: public
DEBUG:eq3bt.connection:Got exception from bluepy while making a request: Failed to connect to peripheral 00:1a:22:13:9c:0f, addr type: public
Traceback (most recent call last):
  File "/home/marco/.local/lib/python3.8/site-packages/eq3bt/connection.py", line 36, in __enter__
    self._conn.connect(self._mac)
  File "/home/marco/.local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/home/marco/.local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:1a:22:13:9c:0f, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marco/.local/bin/eq3cli", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marco/.local/lib/python3.8/site-packages/eq3bt/eq3cli.py", line 34, in cli
    thermostat.update()
  File "/home/marco/.local/lib/python3.8/site-packages/eq3bt/eq3btsmart.py", line 205, in update
    self._conn.make_request(PROP_WRITE_HANDLE, value)
  File "/home/marco/.local/lib/python3.8/site-packages/eq3bt/connection.py", line 71, in make_request
    with self:
  File "/home/marco/.local/lib/python3.8/site-packages/eq3bt/connection.py", line 40, in __enter__
    self._conn.connect(self._mac)
  File "/home/marco/.local/lib/python3.8/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/home/marco/.local/lib/python3.8/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 00:1a:22:13:9c:0f, addr type: public
``` 

This is the environment I'm running commands in:
- ubuntu 20.04 
- python 3.8
- pip 20.0.2
- python-eq3bt==0.1.11
- bluepy==1.3.0

The goal is to add the thermostat to Home Assistant on a Raspberry Pi, but the same error occurs with the home assistant integration.

Is this library compatible with the latest eqiva firmware?

**Comment by marco-gallinari** [comment]
I don't know if this is relevant, but the official Calor BT app is asking for a PIN when establishing connection, the PIN is displayed on the thermostat display.

Has it always been like that? Is this PIN relevant for a succesful connection?

**Comment by rytilahti** [comment]
The error means that it couldn't connect to the device, I cannot recall the internal details right now. Are you able to form a connection using bluetoothctl or gattool (https://www.jaredwolff.com/get-started-with-bluetooth-low-energy/#!)?

The PIN functionality itself does nothing as far as I know, or at least that was the case with the thermostats I had. So it isn't relevant if that hasn't changed since then.

**Comment by marco-gallinari** [comment]
Thank you. 

as a matter of fact, I tried connecting from a windows PC, and it connected without requiring any sort of PIN. 

I'm buying a new BT usb dongle in a couple of days, maybe the laptop running Ubuntu has some issues with the internal card.
I was not able to compile gatttool on ubuntu 20.04, too, so I think I'll use the dongle on a fresh Debian VM. 

I'll let you know once tested.

**Comment by marco-gallinari** [comment]
@rytilahti sorry it took me some time to set up the proper tests.

Turns out the thermostat is actually refusing connections:

![image](https://user-images.githubusercontent.com/5826601/87531839-94ab4a80-c692-11ea-9256-5e5145fb8c60.png)

I already tried switching bluetooth on the eq-3, no results.

Then I factory reset the eq-3, and it disappeared from lescan; it got back after activating pairing on the device, but still cannot connect.

Is there something I need to unlock on the thermostat?

**Comment by marco-gallinari** [comment]
I'm so sorry I didn't realize that the bluetooth service had crashed in the meanwhile. 
With the new dongle and the proper services started, both gatttool and eq3cli are working fine.
I guess I'm having issues with my server then, I'll investigate.
Thank you for your time
Marco

**Comment by rytilahti** [comment]
Glad you got it working! Bluetooth can be sometimes quite unreliable depending on what hardware you have.
