### ISSUE TITLE
Add parameter to allow choosing Bluetooth interface

### ISSUE THREAD

**Issue by Hummel95** [rytilahti/python-eq3bt#43]
Hi there,

first things first: Thanks a lot for your module, I'm using it for quite some time now and I am very happy with it!

I'd like to make a small feature request: 
It would be helpful if you could select the Bluetooth interface that's being used by your module. I saw that bluepy supports this with the `iface` parameter ([here](http://ianharvey.github.io/bluepy-doc/peripheral.html?highlight=btle)) so I am hoping that this is only a small change and easy to implement.

Thanks

**Comment by rytilahti** [comment]
This library is in maintenance mode and I'm not personally interested doing any changes to it, but if you wish to create a PR to add support for this, I can review it and prepare a release.
