### ISSUE TITLE
I need some help understanding the ongoing issue with the Hassio/HA integration

### ISSUE THREAD

**Issue by kaymueller** [rytilahti/python-eq3bt#60]
Hey @rytilahti ,
thanks for your continous work on that library even tho you are not using it yourself anymore. I'm trying to wrap my head around why my thermostats are not working anymore in Homeassistant 2022.08, but it's such a rabbithole right now. 

- Your library (now v0.2?) is part of the HA Core, so everything I had to do last year, was adding some YAML lines and I got the "climate.living_room" thermostat (and three more) I could use for all the good stuff. 
- At some point it got borked because HA changed their way of handling BTLE-Devices with their new Integration and you added these two new backends plus their dependencies and this got also merged into core, right? https://github.com/home-assistant/core/pull/75145
- Then there is the fact that HA is moving away from they YAML-configs which borked it again. And you tried a fix https://github.com/home-assistant/core/pull/74864  but hasn't been merged yet, because it's too much work right now, and also https://github.com/rytilahti/python-eq3bt/issues/59 which tries to just work around it by basically writing a new library than rewriting it?
- https://github.com/home-assistant/core/issues/76040 you suggested to move to a bt-mqtt-gateway as a workaround here but I am not sure if this is still a thing with the issues right now.

Could you provide a timeline of the events and/or give a hint on how to help you out exactly? And do you have a clue on what HA-Version it broke so I could  in the worst event downgrade to that version? Thank you very very much!!!

best regards,
Kay

**Comment by TechHummel** [comment]
Hey @kaymueller,

bluepy, the original backend for handling Bluetooth that eq3bt relies on, was removed from homeassistant with [2022.07](https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes). While @rytilahti added bleak support to eq3bt (bleak is the by homeassistant preferred backend), this does not seem to work well for everyone. In order to make eq3bt work again, #59 needs to be implemented (this is about how bluetooth devices are handled within homeassistant and eq3bt).

Cheers!

**Comment by kaymueller** [comment]
Hi @TechHummel ,
thank you very much. Now I got it. 

Everyone stumbling over this: With the "Terminal & SSH" Add-on from Home Assistant you can just do

`ha core update --version 2022.6.7`

to go back to the last working version. No need to use backups - Tho, you should definitly do one and download it, before doing it.

best regards,
Kay
