### ISSUE TITLE
eq3cli - negative offsets result in error

### ISSUE THREAD

**Issue by IFD3** [rytilahti/python-eq3bt#73]
eq3cli --mac xxx --backend bluepy offset -2 results either in:

 -2 is not a parameter
or when written with "
-2 is not a valid float.

**Comment by rytilahti** [comment]
You could try `eq3cli --mac xxx --backend bluepy offset -- -2` to avoid your shell interpreting the `-2` as an option to the command.

**Comment by IFD3** [comment]
awesome that works, never knew that was an option.
thanks a lot
