### ISSUE TITLE
Failed to install due to bluepy-helper compilation issue

### ISSUE THREAD

**Issue by stefanreimers** [rytilahti/python-eq3bt#8]
I am running a clean install of Hassbian (Home Assistant OS) on a RaspberryPi 3. The command 

`pip install python-eq3bt`

fails when "Running setup.py install for bluepy" with the message

>  Working dir is /tmp/pip-build-x6ukhfdf/bluepy
>     execute make -C ./bluepy clean
>     execute make -C bluepy -j1
>     Failed to compile bluepy-helper. Exiting install.
>     Command was 'make -C bluepy -j1' in /tmp/pip-build-x6ukhfdf/bluepy
>     Return code was 2

I tried the installation with pip as well as pip3 (and sudo).

Any idea how to fix that?
Thanks in advance

**Comment by rytilahti** [comment]
Is this still an issue? Could you do `pip install -e python-eq3bt` to see if it works now, and if not, run that command (`make -C bluepy -j1`) in the source directory?

**Comment by stefanreimers** [comment]
I was able to get it working by making bluepy myself - as you implied.
